apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-run-as-non-root-user
  namespace: memelord-arno
  annotations:
    policies.kyverno.io/title: Require Run As Non-Root User
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must explicitly set runAsUser > 0. Unset runAsUser defaults to root (0) and is rejected.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: run-as-non-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        cel:
          expressions:
            - expression: >-
                object.spec.containers.all(c,
                  has(c.securityContext) && has(c.securityContext.runAsUser) && c.securityContext.runAsUser > 0)
              message: Running as root is not allowed. Each container must set securityContext.runAsUser > 0.
            - expression: >-
                !has(object.spec.initContainers) || object.spec.initContainers.all(c,
                  has(c.securityContext) && has(c.securityContext.runAsUser) && c.securityContext.runAsUser > 0)
              message: Init containers must set securityContext.runAsUser > 0.
