---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        editable: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_DATABASE_TYPE
              value: sqlite3
            - name: GF_DATABASE_PATH
              value: /var/lib/grafana/grafana.db
            - name: GF_SERVER_ROOT_URL
              value: "https://{{ .Values.grafanaHostname }}"
            - name: GF_USERS_DEFAULT_ROLE
              value: "Admin"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "Codemowers"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              value: "contains(groups[*], 'github.com:codemowers:admins') && 'Admin' || Viewer"
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: "openid profile groups"
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: "https://auth.ee-lte-1.codemowers.io/auth"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "http://passmower.passmower/token"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "http://passmower.passmower/me"
            - name: GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL
              value: "https://auth.ee-lte-1.codemowers.io/oidc/sign_out"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-client-{{ .Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name) }}-owner-secrets
                  key: OIDC_CLIENT_ID
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-client-{{ .Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name) }}-owner-secrets
                  key: OIDC_CLIENT_SECRET
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: grafana-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: sqlite
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ printf "%s-tls" (.Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name)) }}
  dnsNames:
    - {{ .Values.grafanaHostname }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.grafanaHostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  tls:
    - secretName: {{ printf "%s-tls" (.Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name)) }}
---
apiVersion: codemowers.cloud/v1beta1
kind: OIDCClient
metadata:
  name: {{ .Values.grafanaOidcName | default (printf "grafana-%s" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
spec:
  displayName: Grafana {{ .Release.Name }}
  uri: https://{{ .Values.grafanaHostname }}/
  redirectUris:
    - https://{{ .Values.grafanaHostname }}/login/generic_oauth
  grantTypes:
    - authorization_code
    - refresh_token
  responseTypes:
    - code
  availableScopes:
    - openid
    - profile
    - groups
  pkce: false
